# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a6f3f501f933714f0ee68e666a4b19903c98c66f159801be47c87d945ef37890ee6ff3945e9d39c0f9de77d72c0800806c87716a5e5936cc0ea489c8acd0104a

test:
  secret_key_base: d612e5e8f87e5873d0771dd70eefee8a5efe5ac57f7e7851110f6e3d963ecf0fb4fb75c9a97502ea8055e3993c7e4ebc0b8932092041519ae88c558931d79937

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
